"use client";

import { use } from "react";
import { Navbar } from "@/components/navbar";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useDoc, useFirestore, useMemoFirebase } from "@/firebase";
import { doc } from "firebase/firestore";
import { Loader2, MapPin, BedDouble, Bath, Square, TrendingDown, DollarSign, Calendar, ShieldCheck, User, MessageCircle } from "lucide-react";
import Image from "next/image";
import { PlaceHolderImages } from "@/lib/placeholder-images";
import { useToast } from "@/hooks/use-toast";

export default function PropertyDetailsPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const db = useFirestore();
  const { toast } = useToast();

  const propertyRef = useMemoFirebase(() => {
    return doc(db, "public_property_listings", id);
  }, [db, id]);

  const { data: property, isLoading } = useDoc(propertyRef);

  const handleMakeOffer = () => {
    toast({
      title: "Coming Soon",
      description: "Direct offer submittal is being finalized for your market.",
    });
  };

  if (isLoading) return <div className="min-h-screen flex items-center justify-center"><Loader2 className="animate-spin h-12 w-12 text-primary" /></div>;
  if (!property) return <div className="min-h-screen flex items-center justify-center">Property not found.</div>;

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <main className="container mx-auto px-4 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-6">
            <div className="relative aspect-video rounded-3xl overflow-hidden border shadow-lg">
              <Image 
                src={PlaceHolderImages.find(img => img.id.includes("house-listing"))?.imageUrl || "https://picsum.photos/seed/details/1200/800"} 
                alt={property.title} 
                fill 
                className="object-cover"
              />
              <div className="absolute top-6 left-6 flex gap-3">
                <Badge className="bg-primary text-white text-md px-4 py-1">{property.foreclosureStatus}</Badge>
                <Badge variant="secondary" className="bg-white/90 backdrop-blur-sm text-md px-4 py-1">Active Listing</Badge>
              </div>
            </div>

            <div className="space-y-4">
              <h1 className="text-4xl font-bold font-headline">{property.addressStreet}</h1>
              <div className="flex items-center text-muted-foreground gap-4">
                <div className="flex items-center gap-1"><MapPin className="h-4 w-4 text-accent" /> {property.addressCity}, {property.addressState} {property.addressZip}</div>
                <div className="flex items-center gap-1"><Calendar className="h-4 w-4" /> Built in {property.yearBuilt}</div>
              </div>
            </div>

            <div className="grid grid-cols-3 gap-6 p-6 bg-white rounded-2xl border shadow-sm">
               <div className="text-center">
                 <BedDouble className="h-6 w-6 mx-auto mb-2 text-primary" />
                 <div className="font-bold text-xl">{property.bedrooms}</div>
                 <div className="text-sm text-muted-foreground">Bedrooms</div>
               </div>
               <div className="text-center border-x">
                 <Bath className="h-6 w-6 mx-auto mb-2 text-primary" />
                 <div className="font-bold text-xl">{property.bathrooms}</div>
                 <div className="text-sm text-muted-foreground">Bathrooms</div>
               </div>
               <div className="text-center">
                 <Square className="h-6 w-6 mx-auto mb-2 text-primary" />
                 <div className="font-bold text-xl">{property.squareFootage}</div>
                 <div className="text-sm text-muted-foreground">Sq. Feet</div>
               </div>
            </div>

            <section className="space-y-4">
              <h2 className="text-2xl font-bold font-headline">Property Description</h2>
              <p className="text-muted-foreground leading-relaxed whitespace-pre-wrap">
                {property.description}
              </p>
            </section>

            <Card className="border-accent/30 bg-accent/5">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-primary">
                  <ShieldCheck className="h-6 w-6" /> AI-Driven Opportunity Analysis
                </CardTitle>
                <CardDescription>Generated by HomeSolve AI based on market data and condition reports.</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                 <div className="flex justify-between items-center p-4 bg-white rounded-xl border">
                    <span className="font-medium">AI Estimated Value</span>
                    <span className="text-2xl font-bold text-primary">${property.aiQuickSaleValuation?.toLocaleString()}</span>
                 </div>
                 <p className="text-sm text-muted-foreground italic">
                   This valuation accounts for the current {property.foreclosureStatus} status and target quick-sale timelines common in this zip code.
                 </p>
              </CardContent>
            </Card>
          </div>

          {/* Sidebar Action Card */}
          <div className="space-y-6">
            <Card className="shadow-xl border-2 border-primary/20 sticky top-24">
              <CardHeader>
                <div className="text-sm text-muted-foreground font-medium uppercase tracking-wider mb-1">Asking Price</div>
                <div className="text-4xl font-bold text-primary flex items-center">
                  <DollarSign className="h-8 w-8 -ml-1" />
                  {property.askingPrice?.toLocaleString()}
                </div>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Listing Type</span>
                    <span className="font-medium">{property.propertyType}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Status</span>
                    <Badge variant="outline" className="text-accent border-accent">{property.status}</Badge>
                  </div>
                </div>

                <div className="pt-6 border-t space-y-3">
                  <Button className="w-full h-12 rounded-full text-lg" onClick={handleMakeOffer}>
                    Submit Cash Offer
                  </Button>
                  <Button variant="outline" className="w-full h-12 rounded-full" onClick={handleMakeOffer}>
                    <MessageCircle className="mr-2 h-4 w-4" /> Message Homeowner
                  </Button>
                </div>
              </CardContent>
              <CardFooter className="bg-muted/50 p-4">
                 <div className="flex items-center gap-3">
                   <div className="h-10 w-10 rounded-full bg-gray-200 flex items-center justify-center text-gray-500">
                     <User className="h-6 w-6" />
                   </div>
                   <div className="text-sm">
                     <p className="font-bold">Listing Verified</p>
                     <p className="text-xs text-muted-foreground">Homeowner ID: {property.homeownerId.substring(0, 8)}...</p>
                   </div>
                 </div>
              </CardFooter>
            </Card>

            <Card>
              <CardContent className="p-6 text-center space-y-4">
                <TrendingDown className="h-12 w-12 mx-auto text-accent/40" />
                <h3 className="font-bold">Investor Insight</h3>
                <p className="text-sm text-muted-foreground">
                  Properties in {property.addressCity} with this foreclosure status typically close 30% faster on HomeSolve compared to traditional MLS listings.
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </main>
    </div>
  );
}
