default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(scheme: "App")
    upload_to_testflight
  end

  desc "Deploy a new version to the App Store"
  lane :deploy do
    build_app(scheme: "App")
    upload_to_app_store
  end
end
