default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Google Play Internal Track"
  lane :beta do
    gradle(task: "bundle", build_type: "Release")
    upload_to_play_store(track: "internal", skip_upload_apk: true)
  end

  desc "Deploy a new version to the Google Play Store"
  lane :deploy do
    gradle(task: "bundle", build_type: "Release")
    upload_to_play_store
  end
end
